# Generated by Django 5.2 on 2025-06-15 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=300)),
                ('details', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='course_img')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(choices=[('Admin Panel', 'Admin Panel'), ('Mentor Wing', 'Mentor Wing'), ('IT Wing', 'IT Wing'), ('Executive Wing', 'Executive Wing'), ('Public Relations Wing', 'Public Relations Wing')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('page_subtitle', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentFacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(choices=[('CHEIF ADVISOR', 'CHEIF ADVISOR'), ('CHEIF PATRON', 'CHEIF PATRON')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(default='Lecturer, Dept of CSE, KiU', max_length=150)),
                ('image', models.ImageField(upload_to='faculty/')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('page_subtitle', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('PROGRAMMING', 'PROGRAMMING'), ('HACKATHON', 'HACKATHON'), ('WEB', 'WEB'), ('FEST', 'FEST'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormerExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(choices=[('Admin Panel', 'Admin Panel'), ('Mentor Wing', 'Mentor Wing'), ('IT Wing', 'IT Wing'), ('Executive Wing', 'Executive Wing'), ('Public Relations Wing', 'Public Relations Wing')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('page_subtitle', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FormerFacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel', models.CharField(choices=[('CHEIF ADVISOR', 'CHEIF ADVISOR'), ('CHEIF PATRON', 'CHEIF PATRON')], max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(default='Lecturer, Dept of CSE, KiU', max_length=150)),
                ('image', models.ImageField(upload_to='faculty/')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('page_title', models.CharField(blank=True, max_length=200)),
                ('page_subtitle', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('file', models.FileField(blank=True, null=True, upload_to='notices')),
            ],
        ),
        migrations.CreateModel(
            name='ShowCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='showcase/')),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_img')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='root.event')),
            ],
        ),
    ]
