# Generated by Django 5.2 on 2025-05-05 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_alter_notice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='course_img'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(upload_to='attachments'),
        ),
    ]
