# Generated by Django 5.2 on 2025-05-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0003_alter_course_image_alter_notice_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('PROGRAMMING', 'PROGRAMMING'), ('HACKATHON', 'HACKATHON'), ('WEB', 'WEB'), ('FEST', 'FEST'), ('OTHERS', 'OTHERS')], max_length=20)),
                ('image', models.ImageField(upload_to='event_img')),
            ],
        ),
    ]
