# Generated by Django 5.2 on 2025-05-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_remove_event_image_eventimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
