# Generated by Django 5.2 on 2025-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_event_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(upload_to='notices'),
        ),
    ]
