# Generated by Django 5.2 on 2025-05-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_panel_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='panel',
            name='page_subtitle',
            field=models.CharField(default='Acting Panel (Effective from November 2024)', max_length=300),
        ),
        migrations.AddField(
            model_name='panel',
            name='page_title',
            field=models.CharField(default='EXECUTIVE BODY 2024', max_length=200),
        ),
    ]
