# Generated by Django 5.2 on 2025-05-06 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0009_panel_page_subtitle_panel_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panel',
            name='page_subtitle',
            field=models.CharField(default='Acting Panel (Effective from..)', max_length=300),
        ),
        migrations.AlterField(
            model_name='panel',
            name='page_title',
            field=models.CharField(default='EXECUTIVE BODY 20..', max_length=200),
        ),
    ]
