# Generated by Django 5.2 on 2025-05-07 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_alter_panel_page_subtitle_alter_panel_page_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='ExecutiveMember',
        ),
        migrations.RenameModel(
            old_name='Panel',
            new_name='ExecutivePanel',
        ),
    ]
