# Generated by Django 5.2 on 2025-05-07 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_rename_member_executivemember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('page_title', models.CharField(default='FACULTY PANEL', max_length=200)),
                ('page_subtitle', models.CharField(default='Acting Panel (Effective from...)', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(default='Lecturer, Dept of CSE, KiU', max_length=150)),
                ('image', models.ImageField(upload_to='faculty/')),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='root.facultypanel')),
            ],
        ),
    ]
