# Generated by Django 5.2 on 2025-05-07 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_facultypanel_facultymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notices'),
        ),
    ]
